### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by jacobmllr95** [alexsasharegan/vue-functional-data-merge#18]
Since Vue 3 changed the [VNode props format](https://v3.vuejs.org/guide/migration/render-function-api.html#vnode-props-format), this library is only compatible with Vue 2.

It would be awesome to have a new major version with Vue 3 support.

**Comment by alexsasharegan** [comment]
I will check out how things should change to accommodate the new props interface! I won't get to it right away, so perhaps you can point me to where I could do a vue version check to switch the merge function accordingly? Hopefully there's something simple like `Vue.version` I can check.

**Comment by alexsasharegan** [comment]
Okay, yup. `Vue.version` is a thing. Not seeing it documented, but it's on the global.

**Comment by alexsasharegan** [comment]
Looks like the safest way to do this is a new version like you suggested. I thought it might be nice for the library to detect and use the right merge strategy, but that creates a big question of accessing the Vue global to determine version, and that often leads to build hassles and sometimes double packaging all of Vue.

**Comment by jacobmllr95** [comment]
@alexsasharegan Yeah, I think this will be the way to go.

**Comment by alexsasharegan** [comment]
Available as `vue-functional-data-merge@next`

```sh
npm info vue-functional-data-merge@next
```
