### ISSUE TITLE
Merge fail when key exists but value is undefined

### ISSUE THREAD

**Issue by AlexandreBonaventure** [alexsasharegan/vue-functional-data-merge#5]
suppose 
```
mergeData({
  on: undefined
}, { staticClass: 'foo'})
```
it will raise a `Cannot convert null or undefined to object `

ps: Great lib, cheers !

**Comment by AlexandreBonaventure** [comment]
Wow, that was quick ! thx

**Comment by alexsasharegan** [comment]
You caught me at the right time! I'll have this merged and a new patch version out shortly. Good catch!

**Comment by alexsasharegan** [comment]
Go ahead and try `v2.0.4`

**Comment by AlexandreBonaventure** [comment]
It is fixed indeed, thank you
